export * from './main-page/MainPage'
export * from './registration/Registration'
export * from './authorization/Authorization'
export * from './event/Event'
export * from './events/Events'
export * from './event-form/EventForm'
